project:
  type: website
  output-dir: docs

title: "Mach Superstudio"
navbar:
  left:
    - text: "Clustering"
      href: index.qmd
    - text: "Index Draft"
      href: /notebooks/retreat_index.html
